name: Custom CD

on:
    push:
      branches:
        - main

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: "docker261319/nuxt3image"

jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v4
      - name: Login to hub.docker.com
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Deploy to Coolify
        run: | 
         curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'