name: Custom CD

on:
    push:
      branches:
        - main

jobs:
    run_pull:
      name: run pull
      runs-on: ubuntu-latest
      
      steps:
      - name: install ssh keys & checkout from repo
        uses: ./.github/actions/ssh-init-checkout